mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls')),
]

polls/urls.py
from django.urls import path


from . import views

app_name = 'polls'
urlpatterns = [
	path('',views.index,name='index'),
	path('specifics/<int:question_id>/', views.detail, name='detail'),
	path('<int:question_id>/results/', views.results, name='results'),
	path('<int:question_id>/vote/', views.vote, name='vote'),
	path('polls/latest.html',views.index),
	

]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone


# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length = 200)
	pub_date = models.DateTimeField('date publication')
	def __str__(self):
		return self.question_text
	def publication_recente(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete = models.CASCADE)
	choice_text = models.CharField(max_length= 200)
	votes = models.IntegerField(default = 0)
	def __str__(self):
		return self.choice_text

polls/templates/models.py
from django.db import models

# Create your models here.

polls/templates/polls/models.py
from django.db import models

# Create your models here.

polls/templates/polls/views.py
from django.shortcuts import render

# Create your views here.

polls/templates/views.py
from django.shortcuts import render

# Create your views here.

polls/views.py
from django.http import HttpResponse
from django.template import loader
from django.http import Http404
from django.shortcuts import get_object_or_404,  render

from .models import Question

def index(request):
	latest_question_list = Question.objects.order_by('-pub_date')[:5]
	#template = loader.get_template('polls/index.html')
	context = {
		'latest_question_list': latest_question_list,
		}
   	 return render(request, 'polls/index.html', context)
def detail(request, question_id):
	try:
		#question= Question.objects.get(pk=question_id)
		question = get_object_or_404(Question, pk=question_id)
	except Question.DoesNotExist:
		raise Http404("Question does not exist")
	return render(request, 'polls/detail.html', {'question': question})
#	return HttpResponse("affichons cette question %s." % question_id)
def results(request, question_id):
	response = "affichons les resultats de cette question %s."
	return HttpResponse(response % question_id)

def vote(request, question_id):
	return HttpResponse("votons pour une question %s." % question_id)

polls/templates/polls/detail.html
{{question}}
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

polls/templates/polls/index.html
{% if latest_question_list %}
	<ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
<li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
<li><a href="{% url 'detail' question.id %}">{{ question.question_text }}</a></li>
<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>